# 将 `baseurl` 设置为您的根域名
# 如果将其设置为“/”，则在生产中共享图标将无法正常工作
baseurl = "https://myBlog.github.io/"  # 包括尾部斜杠
# title = "Clarity"  # 直接从 config/_default/languages.toml 编辑 # 或者取消注释此行并从上述文件中删除 `title` 条目。
copyright = "版权所有 © 2008–2018，Steve Francia 和 Hugo 作者；保留所有权利。"
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"# 取消以下行的注释以启用 Google Analytics 跟踪
# googleAnalytics = "UA-123-45"


[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mobileNavigation = "left" # 移动导航菜单将打开到屏幕左侧。
#bile nav menu will open to the left of the screen.
